(function exposeStory(root) {
  "use strict";

  const BASE_PROMPT = "16:10，1280×800，高完成度电影感纪实插画；深墨黑、暖纸米色、荧光青绿、电光蓝；真实中国校园与城市空间，人物自然、手部准确、留出移动端安全裁切；不要任何可读文字、字母、数字、水印、UI 或标志。";
  const scenes = [
    {
      id: 1,
      src: "assets/story/01-night-deadline.webp",
      chapter: "起点",
      phase: "conflict",
      alt: "夜晚宿舍里，林知夏面对堆满讲义的书桌，周宁递来一杯水",
      caption: "三天后要答辩，资料很多，但哪些可信、该先做什么都还不清楚。",
      prompt: `林知夏，22 岁中国女大学生，齐肩黑发、圆框眼镜、米白针织衫外搭深蓝牛仔衬衫；周宁，短黑发、灰色卫衣。中国大学宿舍夜晚，木桌、台灯、电脑和散乱课程材料，林知夏疲惫但专注，周宁递水。${BASE_PROMPT}`,
    },
    {
      id: 2,
      src: "assets/story/02-undergraduate-brief.webp",
      chapter: "起点",
      phase: "undergraduate",
      alt: "清晨教室里，林知夏和周宁一起查看刚收到的课程评分表",
      caption: "本科生的起点：先看清评分点、听众与截止时间。",
      prompt: `同一林知夏与周宁。中国大学清晨教室，老师刚发下课程答辩任务，两人在前排查看评分表，神情从茫然转为警觉。${BASE_PROMPT}`,
    },
    {
      id: 3,
      src: "assets/story/03-postgraduate-boundary.webp",
      chapter: "起点",
      phase: "postgraduate",
      alt: "研究生陈默在高校图书馆中界定研究汇报的论证边界",
      caption: "研究生的起点：先限定问题、证据口径与论证边界。",
      prompt: `中国男研究生陈默，25 岁，短黑发、细框眼镜、深灰圆领毛衣；高校图书馆档案区，桌上是论文、访谈转写与索引卡，他为研究汇报界定问题边界。${BASE_PROMPT}`,
    },
    {
      id: 4,
      src: "assets/story/04-early-career-brief.webp",
      chapter: "起点",
      phase: "early-career",
      alt: "初入职场的周宁在小型产品团队晨会上接到用户调研汇报任务",
      caption: "职场新人的起点：先对齐决策人、使用场景和交付时间。",
      prompt: `周宁，23 岁，短黑发、灰色卫衣外搭黑色夹克；中国城市小型产品团队清晨会议，她接到用户调研汇报任务，桌上有录音笔与打印材料。${BASE_PROMPT}`,
    },
    {
      id: 5,
      src: "assets/story/05-evidence-priority.webp",
      chapter: "定向",
      phase: "evidence",
      alt: "林知夏与周宁在图书馆逐页核对原始研究报告",
      caption: "选择“证据可信”，原文位置会先于表达样式进入计划。",
      prompt: `同一林知夏与周宁。图书馆靠窗长桌，林知夏逐页核对原始研究报告，用青绿色透明索引标记来源，周宁在对面复核。${BASE_PROMPT}`,
    },
    {
      id: 6,
      src: "assets/story/06-structure-priority.webp",
      chapter: "定向",
      phase: "structure",
      alt: "林知夏和周宁在空教室白板前把混乱卡片重排成清晰路径",
      caption: "选择“结构清晰”，先把听众的问题排成能跟上的顺序。",
      prompt: `同一人物。大学空教室傍晚，两人在白板前把无字卡片重排为三列叙事路径，移走多余卡片，用电光蓝线连接关键节点。${BASE_PROMPT}`,
    },
    {
      id: 7,
      src: "assets/story/07-delivery-priority.webp",
      chapter: "定向",
      phase: "delivery",
      alt: "清晨宿舍里，林知夏用计时器筛出必须完成的三项任务",
      caption: "选择“按时交付”，先守住最小可交版本，再处理可选内容。",
      prompt: `同一人物。宿舍清晨，林知夏把资料分成必须处理与稍后完善两摞，用实体计时器短时冲刺；周宁收走多余材料。${BASE_PROMPT}`,
    },
    {
      id: 8,
      src: "assets/story/08-source-conflict.webp",
      chapter: "取证",
      phase: "conflict",
      alt: "林知夏在散乱资料中发现不同来源互相冲突",
      caption: "真正的冲突不是写不出来，而是现有材料彼此说法不一。",
      prompt: `同一人物。宿舍桌上有讲义、截图、录音笔、U 盘与手机照片，林知夏拿起两份矛盾材料皱眉，周宁寻找原始文件。${BASE_PROMPT}`,
    },
    {
      id: 9,
      src: "assets/story/09-source-ingestion.webp",
      chapter: "取证",
      phase: "ingestion",
      alt: "林知夏和周宁把纸质、录音和照片资料整理进电脑",
      caption: "先让每份材料有来源、有状态，再决定它能不能支持结论。",
      prompt: `同一人物。林知夏把纸质讲义、录音和照片整理进电脑，周宁拍摄一页材料，桌面从混乱转为有序；屏幕仅有抽象状态点。${BASE_PROMPT}`,
    },
    {
      id: 10,
      src: "assets/story/10-contradiction-found.webp",
      chapter: "取证",
      phase: "verification",
      alt: "深夜图书馆里，林知夏和周宁对照两张走势相反的图表",
      caption: "生成之前先发现矛盾，能避免把冲突材料包装成确定结论。",
      prompt: `同一人物。图书馆深夜，两页来源的无字图表走势相反，林知夏停笔，周宁俯身共同检查原始文件。${BASE_PROMPT}`,
    },
    {
      id: 11,
      src: "assets/story/11-evidence-route.webp",
      chapter: "比较",
      phase: "evidence",
      alt: "桌面上从原始材料到证据卡再到结论卡形成严谨路径",
      caption: "证据先行：可靠性最高，代价是前两天推进更慢。",
      prompt: `同一人物。大学研讨室，桌上形成原始材料、青绿色证据卡、白色结论卡依次连接的路径，两人逐张核对。${BASE_PROMPT}`,
    },
    {
      id: 12,
      src: "assets/story/12-evidence-tradeoff.webp",
      chapter: "比较",
      phase: "evidence-risk",
      alt: "深夜里证据卡已排齐，但仍有许多空白页面等待完成",
      caption: "可信度上升的同时，时间余量正在下降。",
      prompt: `同一人物。深夜，证据卡已整齐排列，但空白页面仍很多，墙上实体钟接近深夜，周宁困倦，林知夏继续核对。${BASE_PROMPT}`,
    },
    {
      id: 13,
      src: "assets/story/13-structure-route.webp",
      chapter: "比较",
      phase: "structure",
      alt: "林知夏和周宁横向比较三条不同的无字叙事方案",
      caption: "结构先行：更容易讲清楚，但锁定前必须补齐来源缺口。",
      prompt: `同一人物。明亮空教室，两人把三条不同叙事方案横向铺在长桌，移动开场卡并模拟讲述节奏。${BASE_PROMPT}`,
    },
    {
      id: 14,
      src: "assets/story/14-structure-tradeoff.webp",
      chapter: "比较",
      phase: "structure-risk",
      alt: "清晰故事板中仍有几张结论卡缺少来源支撑",
      caption: "讲得顺不等于证据够，空白来源必须在确认前暴露出来。",
      prompt: `同一人物。墙面故事板顺序流畅，但几张结论卡后方只有空白来源夹，林知夏与周宁意识到仍需补证据。${BASE_PROMPT}`,
    },
    {
      id: 15,
      src: "assets/story/15-delivery-route.webp",
      chapter: "比较",
      phase: "delivery",
      alt: "林知夏和周宁用计时器完成三页最小可交版本",
      caption: "交付先行：更能守住截止时间，但会压缩扩展与润色。",
      prompt: `同一人物。宿舍午后，两人用计时器完成最小可交版本，关键三页进入文件夹，次要素材被放入稍后处理的无字盒。${BASE_PROMPT}`,
    },
    {
      id: 16,
      src: "assets/story/16-delivery-tradeoff.webp",
      chapter: "比较",
      phase: "delivery-risk",
      alt: "核心小册已完成，但桌边仍有许多来不及润色的素材",
      caption: "按时完成不代表完美，必须主动承认被压缩的部分。",
      prompt: `同一人物。三页核心小册已完成，旁边仍有漂亮但未处理的视觉素材和空白引用卡；计时器即将到点。${BASE_PROMPT}`,
    },
    {
      id: 17,
      src: "assets/story/17-route-comparison.webp",
      chapter: "抉择",
      phase: "compare",
      alt: "一张长桌上并排摆着证据、结构和交付三条路线",
      caption: "三条路线放在同一量尺下比较，没有三个“都很好”的假选择。",
      prompt: `同一人物。研讨室长桌分成三条平行路线：密集证据卡、清晰故事板、精简三页交付夹与计时器；两人持相同评估筹码比较。${BASE_PROMPT}`,
    },
    {
      id: 18,
      src: "assets/story/18-human-confirmation.webp",
      chapter: "抉择",
      phase: "confirm",
      alt: "林知夏亲手把绿色方块筹码放到选定路线前",
      caption: "推荐只是候选，最终路线必须由使用者明确确认。",
      prompt: `同一人物。林知夏亲手把荧光青绿色方块筹码放到选定路线前，并把对应资料夹拉到面前；其余路线被保留可回看。${BASE_PROMPT}`,
    },
    {
      id: 19,
      src: "assets/story/19-checkable-draft.webp",
      chapter: "成形",
      phase: "draft",
      alt: "林知夏在电脑上编辑有证据连接点的可检查初稿",
      caption: "先做出完整可检查的一版，再让修改针对真实内容发生。",
      prompt: `同一人物。图书馆工作位，林知夏编辑一组结构清晰的抽象页面，桌边摆着故事板、来源卡与逐页讲稿，周宁检查顺序。${BASE_PROMPT}`,
    },
    {
      id: 20,
      src: "assets/story/20-verification.webp",
      chapter: "成形",
      phase: "verify",
      alt: "两人逐页检查数字、图表和来源，并把问题页面单独放置",
      caption: "核验不是一键通过：发现问题、修正、再检查。",
      prompt: `同一人物。宿舍最后检查台，林知夏核对数字、图表与来源，周宁把问题页面翻到一边；电脑仅显示抽象检查矩阵。${BASE_PROMPT}`,
    },
    {
      id: 21,
      src: "assets/story/21-rehearsal.webp",
      chapter: "反馈",
      phase: "rehearsal",
      alt: "林知夏在小教室试讲，同学举手追问，周宁记录时间",
      caption: "真实使用一次，才能知道页面是否说得清、时间是否够。",
      prompt: `同一人物。大学小教室，林知夏在投影前试讲，周宁持计时器与反馈卡，另有同学举手追问，她回到证据夹回答。${BASE_PROMPT}`,
    },
    {
      id: 22,
      src: "assets/story/22-specific-feedback.webp",
      chapter: "反馈",
      phase: "feedback",
      alt: "周宁用两张图卡向林知夏说明信息太密和证据清楚的具体反馈",
      caption: "“信息太密”会改变结构；“证据不足”会改变取证顺序。",
      prompt: `同一人物。演练后复盘，周宁把代表信息太密的拥挤卡与代表证据清楚的青绿色卡递给林知夏，她认真记录。${BASE_PROMPT}`,
    },
    {
      id: 23,
      src: "assets/story/23-feedback-rerank.webp",
      chapter: "反馈",
      phase: "rerank",
      alt: "次日清晨，林知夏删除拥挤页面并把核心证据提前",
      caption: "反馈进入下一轮后，候选排序、页面密度与第一步一起变化。",
      prompt: `同一人物。次日清晨，故事板被重新排序，林知夏移除拥挤页面、把核心证据提前，周宁重新计时，旧版留作对照。${BASE_PROMPT}`,
    },
    {
      id: 24,
      src: "assets/story/24-trusted-delivery.webp",
      chapter: "交付",
      phase: "delivery-complete",
      alt: "明亮教室里，老师翻看交付册与证据索引，林知夏完成汇报",
      caption: "交得出去，也经得起追问：成果、来源与过程一起带走。",
      prompt: `同一人物。明亮答辩教室，林知夏完成汇报，老师翻看交付册与证据索引，周宁在后排微笑，桌上有 U 盘、打印稿与来源夹。${BASE_PROMPT}`,
    },
  ];

  root.ZuochengStory = Object.freeze({
    get(id) {
      return scenes.find((scene) => scene.id === Number(id)) || scenes[0];
    },
    scenes: Object.freeze(scenes.map((scene) => Object.freeze(scene))),
  });
})(typeof globalThis === "object" ? globalThis : this);
